storageClass: gp2
jenkinsUrl: https://spin-jenkins.cx-alpha0.com
serviceAccount:
  create: true
  name: jenkins
  annotations: {}

controller:
  servicePort: 8080
  serviceType: nodePort
  ingress:
    enabled: false
    paths: []
    apiVersion: "networking.k8s.io/v1"
    labels: {}
    annotations: 
          kubernetes.io/ingress.class: alb
          alb.ingress.kubernetes.io/scheme: internet-facing
          alb.ingress.kubernetes.io/target-type: instance
          alb.ingress.kubernetes.io/healthcheck-path: /
    hostName: spin-jenkins.cx-alpha0.com
