storageClass: gp2
jenkinsUrl: https://spin-jenkins.cx-alpha0.com
serviceAccount:
  create: true
  name: jenkins
  annotations: {}

controller:
  servicePort: 8080
  ingress:
    enabled: true
    paths:[]
    apiVersion: "networking.k8s.io/v1"
    labels: {}
    annotations: {}
    hostName: spin-jenkins.cx-alpha0.com
