torageClass: openebs-hostpath
serviceAccount:
  create: false
  name: jenkins
  annotations: {}
  ingress:
    enabled: true
    paths: 
     - backend:
         serviceName: jenkins
         servicePort: 8080
    apiVersion: "networking.k8s.io/v1"
    labels: {}
    annotations: {}
    hostName: spin-jenkins.mirv.ninja
