storageClass: gp2
jenkinsUrl: https://spin-jenkins.cx-alpha0.com
serviceAccount:
  create: true
  name: jenkins
  annotations: {}
  ingress:
    enabled: false
    paths: 
     - backend:
         serviceName: jenkins
         servicePort: 8080
    apiVersion: "networking.k8s.io/v1"
    labels: {}
    annotations: {}
    hostName: spin-jenkins.cx-alpha0.com
